# Configuration for recording alignment dataset
dataset:
  path: "./data/duck"

robot:
  type: "xarmsim"
  gripper_open_pos: 0.008
  gripper_close_pos: -0.008

trajectory:
  z_step: 0.0007
  radius_step: 0.001
  num_steps: 100
  cone_angle: 30.0
  visible_sweep: 60.0
  viewing_angle_offset: -120.0
  angular_resolution: 10.0
  include_cone_poses: false
  lift_height_before_spiral: 0.01

episodes: 20
lin_tol_alignment: 0.015
ang_tol_alignment: 0.015
lin_tol_trajectory: 0.05
ang_tol_trajectory: 0.05

