# Configuration for training AlignNet model
dataset:
  path: "./data/duck"

model:
  backbone: "efficientnet_b0"
  backbone_weights: "DEFAULT"
  use_vector_input: false
  fc_layers: [256, 128]
  vector_hidden_dim: 64
  output_dim: 9
  feature_agg: "mean"

output_path: "alignnet_model.pth"
batch_size: 8
learning_rate: 0.0001
epochs: 100
test_size: 0.2
random_seed: 42

